### ISSUE TITLE
/bpftrace/include/clang_workarounds.h:14:10: fatal error: 'linux/types.h' file not found

### ISSUE THREAD

**Issue by wangzhangjun** [facebookexperimental/ExtendedAndroidTools#37]
when I build successful bpftools-arm64.tar.gz.

in adb shell run : /data/local/tmp/bpftools/bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'

the error: 
/bpftrace/include/clang_workarounds.h:14:10: fatal error: 'linux/types.h' file not found

**Comment by michalgr** [comment]
Hi ! Thank you for reporting.

When BTF is not available in your kernel then bpftrace needs access to kernel headers. You can either set [`BPFTRACE_KERNEL_SOURCE`](https://github.com/iovisor/bpftrace/blob/3cd853f81791a9305542ed6ddfeee10c8d088022/docs/reference_guide.md#2-kernel-headers-not-found) env variable to point bpftrace to kernel headers, or you can compile kernel with `CONFIG_IKHEADERS` option, so that bpftrace can extract them from `/sys/kernel/kheaders.tar.xz` (you might need to set `TMPDIR` env variable to point to `/data/local/tmp`)
